### PR TITLE
Highlight text token if available

### PR DESCRIPTION
**Pull request by guilhermesimoes**
Since `ruby -wc` does not return column numbers, the best we can do for now is parse the warning messages and highlight some text tokens.

Before:
screen shot 2017-05-04 at 16 40 23

After:
screen shot 2017-05-04 at 16 39 17

### CODE REVIEW

**Comment by guilhermesimoes** [comment]
This is still a WIP as I may have missed a few other warnings that can also be highlighted.

**Comment by guilhermesimoes** [comment]
Everything should be good now!

**Comment by kaste** [comment]
Hi. Sorry this repo obviously had no maintainer at that time.

LGTM. @braver ship it!?

**Comment by braver** [comment]
I don’t know anything about Ruby or these changes. I’ll ship it and give @guilhermesimoes access to the repo so he can perhaps make changes later if the need arises.

**Pull request merged**
